# this is my first notebook 

latex: 
$$ 
NegEnt = \sum x \log x 
$$

In [1]:
import numpy as np
print(np.empty((2,2)))

[[1.78881228e+161 6.01334434e-154]
 [2.52303020e-258 4.47593804e-091]]


# text 


this is mark down 

Pip install jupyterlabthis is another mark down text and this create the markdown file needed

$ x\log x + y\sum^{3}_{4}$ 
and this $\frac{123}{123}$

# this is headlined

![txt](Nents.png)





this is more text 
*bold* a bit more text

In [2]:
np.zeros((1,4))

array([[0., 0., 0., 0.]])

In [3]:
a = 1+ np.zeros((1,4))

In [4]:
for i in a
    print(i)


SyntaxError: invalid syntax (<ipython-input-4-e061ff3174a9>, line 1)

In [6]:
a

array([[1., 1., 1., 1.]])

In [7]:
list(a)


[array([1., 1., 1., 1.])]

In [11]:
a.tobytes()


b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?'

In [12]:
a.tostring()

<ipython-input-12-e9f2153e33bf>:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  a.tostring()


b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?'

In [13]:
a.tolist()

[[1.0, 1.0, 1.0, 1.0]]

$\sum^{123}_{i=1} \frac{123}{543} + log\ x \cdot y$


